const jogos = [
    {
        idjogo: '10',
        data: '27/11/2021',
        dia: 'Sábado',
        hora: '16:00',
        equipeA: 'Renegados',
        placar: 'x',
        equipeB: 'Garra',
        local: 'Vila Olímpica',
        bairro: 'Bairro dos Estados',
    },
    {
        idjogo: '09',
        data: '21/11/2021',
        dia: 'Domingo',
        hora: '17:00',
        equipeA: 'Ancef',
        placar: 'x',
        equipeB: 'Motiva',
        local: 'Vila Olímpica',
        bairro: 'Bairro dos Estados',
    },
    {
        idjogo: '08',
        data: '20/11/2021',
        dia: 'Sábado',
        hora: '08:00',
        equipeA: 'Aeroclube',
        placar: 'x',
        equipeB: 'Manaíra',
        local: 'Vila Olímpica',
        bairro: 'Bairro dos Estados',
    },
    {
        idjogo: '07',
        data: '19/11/2021',
        dia: 'Sexta',
        hora: '10:00',
        equipeA: 'Casel',
        placar: 'x',
        equipeB: 'Avab',
        local: 'Vila Olímpica',
        bairro: 'Bairro dos Estados',
    },
    {
        idjogo: '06',
        data: '14/11/2021',
        dia: 'Domingo',
        hora: '15:00',
        equipeA: 'Calangos',
        placar: 'x',
        equipeB: 'Cangaceiros',
        local: 'Vila Olímpica',
        bairro: 'Bairro dos Estados',
    },
    {
        idjogo: '05',
        data: '13/11/2021',
        dia: 'Sábado',
        hora: '16:00',
        equipeA: 'Smurfs',
        placar: 'x',
        equipeB: 'Valentina',
        local: 'Vila Olímpica',
        bairro: 'Bairro dos Estados',
    },
    {
        idjogo: '04',
        data: '12/11/2021',
        dia: 'Sexta',
        hora: '18:00',
        equipeA: 'NBT',
        placar: 'x',
        equipeB: 'Calangos',
        local: 'Vila Olímpica',
        bairro: 'Bairro dos Estados',
    },
    {
        idjogo: '03',
        data: '07/11/2021',
        dia: 'Domingo',
        hora: '16:00',
        equipeA: 'Jp',
        placar: 'x',
        equipeB: 'Cg',
        local: 'Vila Olímpica',
        bairro: 'Bairro dos Estados',
    },
    {
        idjogo: '02',
        data: '06/11/2021',
        dia: 'Sábado',
        hora: '08:00',
        equipeA: 'Jampa',
        placar: 'x',
        equipeB: 'Campina',
        local: 'Vila Olímpica',
        bairro: 'Bairro dos Estados',
    },
    {
        idjogo: '01',
        data: '05/11/2021',
        dia: 'Sexta',
        hora: '10:00',
        equipeA: 'Facisa',
        placar: 'x',
        equipeB: 'Botafogo',
        local: 'Vila Olímpica',
        bairro: 'Bairro dos Estados',
    },
];

export default jogos;